[[main]]
  name = "GitHub"
  url = "https://github.com/cjlaidevlife"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/laichunjing"
  weight = 20

[[social]]
  name = "CakeResume"
  url = "https://www.cakeresume.com/cjlai?locale=zh-TW"
  weight = 30
